baseURL = "https://blog-6gof9lwqe303e12f-1254205115.tcloudbaseapp.com"
defaultContentLanguage = "zh"
languageCode = 'en-us'
publishdir = 'public'
builddrafts = false
copyright = '本站遵循 <a href="https://creativecommons.org/licenses/by-nc/4.0/" >CC-BY-NC 4.0</a> 协议.'
title = '我思故我在'
theme = 'diary'
canonifyurls = true

[params]
favicon = 'images/favicon.svg'
enableReadingTime = true
enableGitalk = true
subtitle = "cndoit18's Blog"

[params.gitalk]
client_id = '51b47ae3df5c7375bfd1'
client_secret = '80185e2e2cf6a6d758aee5aa35a3c08b5cbca431'
repo = 'blog'
owner = 'cndoit18'

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
url = "/tags"
name = "标签"
weight = 1

[[menu.main]]
url = "/categories"
name = "系列"
weight = 2

[[menu.main]]
url = "/about"
name = "关于"
weight = 3
